name: Build image

on:
  push:
    branches: [ install-packages ]

jobs:
  build-image:
    runs-on: ubuntu-22.04
    steps:
      - name: Check out this repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Build image
        run: |
          cd docker
          chmod +x build.sh
          ./build.sh